version: '3.9'
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    labels:
      - "traefik.http.routers.api.rule=Host(`api.docker.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"